---
- hosts: localhost
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Load vars file
    include_vars: vars.yaml
  - name: Create a Linux Virtual Machine
    vmware_guest:
      hostname: "{{ vars.vcenter_ip }}"
      username: "{{ vars.vcenter_user }}"
      password: "{{ vars.vcenter_pwd }}"
      validate_certs: no
      name: "{{ vars.vm_name }}"
      datacenter: "{{ vars.datacenter }}"
      cluster: "{{ vars.cluster }}"
      folder: "{{ vars.folder }}"
      template: "{{ vars.template }}"
      datastore: "{{ vars.datastore }}"
      annotation: "{{ vars.annotation }}"
      disk:
      - size_gb: "{{ vars.disk1_size }}"
      hardware:
        memory_mb: "{{ vars.memory_mb }}"
        num_cpus: "{{ vars.num_cpus }}"
      networks:
        - name: "{{ vars.portgroup }}"
          ip: "{{ vars.ip_address }}"
          netmask: "{{ vars.netmask }}"
          gateway: "{{ vars.gateway }}"
          dns_servers:
          - "{{ vars.dns1 }}"
          - "{{ vars.dns2 }}"
      customization:
        hostname: "{{ vars.hostname }}"
        dns_servers:
        - "{{ vars.dns1 }}"
        - "{{ vars.dns2 }}"
        domain: "{{ vars.dominio }}"
        password: "{{ domain_pwd }}"
        joindomain: "{{ vars.dominio }}"
        domainadmin: "{{ domain_user }}"
        domainadminpassword: "{{ domain_pwd }}"
        windows_remote_desktop_enabled: true
        windows_remote_desktop_firewall: allow
      wait_for_customization: yes
      wait_for_ip_address: True
      state: poweredon
    delegate_to: localhost
  - name: Add disks to virtual machine
    community.vmware.vmware_guest_disk:
      hostname: "{{ vars.vcenter_ip }}"
      username: "{{ vars.vcenter_user }}"
      password: "{{ vars.vcenter_pwd }}"
      datacenter: "{{ vars.datacenter }}"
      validate_certs: no
      name: "{{ vars.vm_name }}"
      disk:
        - size_gb: "{{ vars.disk2_size }}"
          type: eagerzeroedthick
          datastore: "{{ vars.datastore }}"
          state: present
          scsi_controller: 0
          unit_number: 1
    register: disk_facts

# Configuração do SO
- hosts: win
  become: no
  gather_facts: False
  tasks:

# Desabilita Windows Firewall
  - name: Disable Domain firewall
    win_firewall:
      state: disabled
      profiles:
      - Domain
    tags: disable_firewall

# Configura Timezone
  - name: "Set the TimeZone"
    win_timezone:
      timezone: "E. South America Standard Time"

# Altera letra do CD-ROM de D para E
  - name: Change the CD-ROM from D to E
    win_shell: |
        $cd = $NULL
        $cd = Get-WMIObject -Class Win32_CDROMDrive -ComputerName $env:COMPUTERNAME -ErrorAction Stop
        if ($cd.Drive -eq "D:")
        {
           Write-Output "Changing CD Drive letter from D: to E:"
           Set-WmiInstance -InputObject ( Get-WmiObject -Class Win32_volume -Filter "DriveLetter = 'D:'" ) -Arguments @{DriveLetter='E:'}
        }

# Rescan discos windows
  - name: Get disk facts
    win_disk_facts:

# Inicializa disco da partição D
  - name: Initialize Disk 1
    win_shell: "Initialize-Disk -Number 1"

# Cria partição D
  - name: Create Partition Disk 1 Drive D
    win_partition:
      drive_letter: "D"
      partition_size: -1
      disk_number: "1"

# Formata partição D
  - name: Format the partition as NTFS Drive D
    win_format:
      drive_letter: "D"
      file_system: NTFS
      new_label: APP

# Cria Share temporário com permissão everyone
  - name: Add Install share
    win_share:
      name: install
      description: Config Servidor
      path: C:\Temp
      list: no
      full: Everyone

# Copia script e instalador zabbix
  - name: Copy folder to c:\temp (results in C:\Temp\temp_files)
    win_copy:
      src: /var/www/repo_ansible/install/zabbix #Servidor TPRB2210 - 10.41.22.10
      dest: \\10.41.22.86\install

# Copia script e instalador McAfee
  - name: Copy folder to c:\temp (results in C:\Temp\temp_files)
    win_copy:
      src: /var/www/repo_ansible/install/mcafee #Servidor TPRB2210 - 10.41.22.10
      dest: \\10.41.22.86\install

# Install Zabbix Agent

  - name: Install Zabbix Agent
    win_shell: C:\Temp\zabbix\zabbix_prd.ps1

# Install Zabbix Agent

  - name: Install McAfee Agent
    win_shell: C:\Temp\mcafee\mcafee.ps1

# Remove Share temporário
  - name: Remove previously added share
    win_share:
      name: install
      state: absent

# Remove arquivos diretório C:\Temp
  - name: Remove directory structure
    win_file:
      path: C:\Temp\zabbix
      state: absent