---
- hosts: localhost
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Load vars file
    include_vars: vars.yaml
  - name: Create a Linux Virtual Machine
    vmware_guest:
      hostname: "{{ vars.vcenter_ip }}"
      username: "{{ vars.vcenter_user }}"
      password: "{{ vars.vcenter_pwd }}"
      validate_certs: no
      name: "{{ vars.vm_name }}"
      datacenter: "{{ vars.datacenter }}"
      cluster: "{{ vars.cluster }}"
      folder: "{{ vars.folder }}"
      template: "{{ vars.template }}"
      datastore: "{{ vars.datastore }}"
      annotation: "{{ vars.annotation }}"
      disk:
      - size_gb: "{{ vars.disk1_size }}"
      hardware:
        memory_mb: "{{ vars.memory_mb }}"
        num_cpus: "{{ vars.num_cpus }}"
      networks:
        - name: "{{ vars.portgroup }}"
          ip: "{{ vars.ip_address }}"
          netmask: "{{ vars.netmask }}"
          gateway: "{{ vars.gateway }}"
          dns_servers:
          - "{{ vars.dns1 }}"
          - "{{ vars.dns2 }}"
      customization:
        hostname:  "{{ vars.hostname }}"
        dns_servers:
        - "{{ vars.dns1 }}"
        - "{{ vars.dns2 }}"
      wait_for_customization: yes
      wait_for_ip_address: True
      state: poweredon
    delegate_to: localhost
    register: disk_facts
  - name: Add disks to virtual machine
    community.vmware.vmware_guest_disk:
      hostname: "{{ vars.vcenter_ip }}"
      username: "{{ vars.vcenter_user }}"
      password: "{{ vars.vcenter_pwd }}"
      datacenter: VIVO
      validate_certs: no
      name: "{{ vars.vm_name }}"
      disk:
        - size_gb: "{{ vars.disk2_size }}"
          type: eagerzeroedthick
          datastore: DSC_HOMOLOG
          state: present
          scsi_controller: 0
          unit_number: 1
          scsi_type: 'paravirtual'
  - name: Add disks to virtual machine
    community.vmware.vmware_guest_disk:
      hostname: "{{ vars.vcenter_ip }}"
      username: "{{ vars.vcenter_user }}"
      password: "{{ vars.vcenter_pwd }}"
      datacenter: VIVO
      validate_certs: no
      name: "{{ vars.vm_name }}"
      disk:
        - size_gb: "{{ vars.disk3_size }}"
          type: eagerzeroedthick
          datastore: DSC_HOMOLOG
          state: present
          scsi_controller: 0
          unit_number: 2
          scsi_type: 'paravirtual'