apiVersion: v1
kind: ResourceQuota
metadata:
  name: prbsdconvenios-webapi
  namespace: bff-convenios
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi