apiVersion: v1
kind: ResourceQuota
metadata:
  name: prbsdconvenios-hml-webapi
  namespace: bff-convenios-hml
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi