apiVersion: v1
kind: Service
metadata:
  name: prbsdconvenios-hml-webapi
  namespace: bff-convenios-hml
  labels:
    name: prbsdconvenios-hml-webapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: prbsdconvenios-hml-webapi