apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    name: kubernetes-dashboard
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8443
    protocol: TCP
  selector:
    name: kubernetes-dashboard