---
- hosts: windows_funcao_db_hml
  gather_facts: no
  tasks:

# Inicialização dos discos
  - name: Get disk facts
    win_disk_facts:
  - name: Initialize Disk 1
    win_shell: "Initialize-Disk -Number 1"
  - name: Initialize Disk 2
    win_shell: "Initialize-Disk -Number 2"
  - name: Initialize Disk 3
    win_shell: "Initialize-Disk -Number 3"

# Criação das partições
  - name: Create Partition Disk 1 Drive F - MSSQL
    win_partition:
      drive_letter: "F"
      partition_size: -1
      disk_number: "1"
  - name: Create Partition Disk 2 Drive D - DADOS
    win_partition:
      drive_letter: "D"
      partition_size: -1
      disk_number: "2"
  - name: Create Partition Disk 3 Drive T - TEMPDB
    win_partition:
      drive_letter: "T"
      partition_size: -1
      disk_number: "3"

# Formatação das Partições
  - name: Format the partition as NTFS Drive F
    win_format:
      drive_letter: "F"
      file_system: NTFS
      new_label: MSSQL

  - name: Format the partition as NTFS Drive D
    win_format:
      drive_letter: "D"
      file_system: NTFS
      new_label: DADOS


  - name: Format the partition as NTFS Drive T
    win_format:
      drive_letter: "T"
      file_system: NTFS
      new_label: TEMPDB
      
  - name: Add Install share
    win_share:
      name: install
      description: Config Servidor
      path: C:\Temp
      list: no
      full: Everyone

  - name: Copy folder to c:\temp (results in C:\Temp\temp_files)
    win_copy:
      #src: /mnt/c/Temp/automation/Install/sqlserver
      src: /repo_ansible/install/sqlserver
      dest: \\10.140.10.233\install

# Instalação .Net Framework 3.5

  - name: Install .Net 3.5 from source
    win_feature:
      name: NET-Framework-Core
      source: C:\Temp\sqlserver\sxs
      state: present
    register: result

  - name: Windows | Install DSC resource (SqlServerDsc)
    win_psmodule:
      name: SQLServerDsc
      state: present

  - name: Windows | Find ISO in downloaded media
    win_find:
      paths: C:\Temp\sqlserver
      patterns: '*.iso'
      file_type: file
    register: iso_find

  - name: Windows | Mount ISO image of SQL Server
    win_disk_image:
      image_path: '{{ iso_find.files[0].path }}'
      state: present
    register: mount_info
    changed_when: false

  - name: Windows | Install SQL Server
    win_dsc:
      resource_name: SqlSetup
      Action: Install
      InstanceName: MSSQLSERVER
      SourcePath: '{{ mount_info.mount_paths[0] }}'
      Features: SQLENGINE,FULLTEXT,AS,IS,CONN,BC,SDK
      ProductKey: '{{ mssql_pid | d(omit)}}'
      UpdateEnabled: False
      InstallSharedDir: F:\Program Files\Microsoft SQL Server
      InstallSharedwowDir: F:\Program Files (x86)\Microsoft SQL Server
      InstanceDir: F:\Program Files\Microsoft SQL Server
      SQLCollation: SQL_Latin1_General_CP1_CI_AS
      SQLSysAdminAccounts: prbhomolog.local\TI - InfraSQL,homolog.jm\TI - InfraSQL
      TcpEnabled: True
      SecurityMode: SQL
      SAPwd_username: sa
      SAPwd_password: P4r4n4.2022
      SQLUserDBDir: D:\ParanaBanco\Dados\Data
      SQLUserDBLogDir: D:\ParanaBanco\Dados\Log
      SQLTempDBDir: T:\ParanaBanco\Dados\Data
      SQLTempDBLogDir: T:\ParanaBanco\Dados\Log
      SqlSvcStartupType: Automatic
      AgtSvcStartupType: Automatic
      AsSvcStartupType: Manual
      BrowserSvcStartupType: Disabled
      SqlTempdbFileSize: 512
      SqlTempdbFileGrowth: 512
      SqlTempdbLogFileSize: 512
      SqlTempdbLogFileGrowth: 512
      PsDscRunAsCredential_username: '{{ ansible_user | d(omit) }}'
      PsDscRunAsCredential_password: '{{ ansible_password | d(omit)}}'
  - name: Install SSMS
    win_package:
      path: C:\Temp\sqlserver\SSMS-Setup-18.9.2-ENU.exe
      product_id: SSMS-Setup-18.9.2-ENU
      arguments:
      - /install
      - /quiet
      - /norestart
      state: present

  - name: Unmount ISO
    win_disk_image:
      image_path: '{{ iso_find.files[0].path }}'
      state: absent
  
# Adicionar Grupo DBAs como Administrator Local
  - name: Add Grupo da DBAs no Grupo ADM Local
    win_group_membership:
      name: Administrators
      members:
        - homolog.jm\TI - InfraSQL
        - prbhomolog.local\TI - InfraSQL
      state: present

# Cria usuário local no SQL Server
  - name: Cria usuário local user_azure no SQL Server
    win_command: sqlcmd -i "C:\Temp\sqlserver\adduseradmin.sql"
    register: sqlcmd_out

# Install Zabbix Agent

  - name: Install Zabbix Agent
    win_shell: C:\Temp\sqlserver\zabbix_hml.ps1

# Install McAfee Agent

  - name: Install McAfee Agent
    win_shell: C:\Temp\sqlserver\mcafee.ps1

# Remove Share
  - name: Remove previously added share
    win_share:
      name: install
      state: absent

# Remove diretório SQLSERVER
  - name: Remove directory structure
    win_file:
      path: C:\Temp\sqlserver
      state: absent