variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "vsphere_virtual_machine" {}
variable "VM_IP" {}
variable "netmask" {}
variable "def_gw" {}
variable "VM_name" {}
variable "domain_admin_user" {}
variable "domain_admin_password" {}
variable "dns_domain" {}
variable "domain" {}
variable "dns1" {}
variable "dns2" {}
variable "vCPU" {}
variable "Memory" {}