---

- name: Snapshot Info
  hosts: localhost 
  gather_facts: false
  vars_files: 
    multiple_vms.yml
  tasks: 
  - name: Gather snapshot information about the virtual machine in the given vCenter
    community.vmware.vmware_guest_snapshot_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      datacenter: VIVO
      #folder: "/{{ datacenter_name }}/vm/"
      #name: "{{ guest_name }}"
    delegate_to: localhost
    register: snapshot_info