---
- hosts: win
  become: no
  gather_facts: False
  vars:
  tasks:
  - name: Disable Domain firewall
    win_firewall:
      state: disabled
      profiles:
      - Domain
    tags: disable_firewall
  - name: "Set the TimeZone"
    win_timezone:
      timezone: "E. South America Standard Time"

  - name: Windows | Check for xRemoteDesktopAdmin Powershell module
    win_psmodule:
      name: xRemoteDesktopAdmin
      state: present

  - name: Windows | Enable Remote Desktop
    win_dsc:
      resource_name: xRemoteDesktopAdmin
      Ensure: present
      UserAuthentication: Secure

  - name: Windows | Check for xNetworking Powershell module
    win_psmodule:
      name: xNetworking
      state: present

  - name: Windows | Add Group IT_Admins
    win_group_membership:
      name: Administrators
      members:
        - homolog.jm\HMLFuncaoRDPAdmin
      state: present