kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-user-access-rolebinding
  namespace: portalinstitucional-homolog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-rbac-bffconvenios-read
subjects:
- kind: Group
  namespace: portalinstitucional-homolog
  #name: groupObjectId # Your Azure AD Group Object ID: devaksteam
  name: "95f91059-1537-4f9e-8e3a-080f3a36ca9f"  